/**
 * Demo Data Engine -- date-window anchor.
 *
 * Every fact + seed table generated by the Data Engine must fall inside a
 * single, run-time-computed date window so that demos never drift into
 * stale years (the common 2024-only failure mode).
 *
 * The window is:
 *   start = first day of the most recently completed fiscal year
 *   end   = CURRENT_DATE() (today)
 *
 * When the current fiscal year has fewer than MIN_CURRENT_FY_DAYS elapsed,
 * we extend start back one more FY so narratives have room to breathe
 * (otherwise a run on 2026-01-05 would cover a 5-day YTD slice).
 *
 * All constants are tunable here -- prompts, engine wiring, and validation
 * all resolve their window through this module.
 */

// ---------------------------------------------------------------------------
// Tunable constants
// ---------------------------------------------------------------------------

/**
 * If fewer days than this have elapsed in the current FY, extend the window
 * one additional FY back so the demo has enough history to tell a story.
 */
export const MIN_CURRENT_FY_DAYS = 60;

/** Default fiscal-year start (1 = January = calendar FY). */
export const DEFAULT_FISCAL_YEAR_START_MONTH = 1;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface DemoDateWindow {
  /** ISO 8601 YYYY-MM-DD at the start of the window. */
  startDate: string;
  /** ISO 8601 YYYY-MM-DD at the end of the window (today). */
  endDate: string;
  /** Inclusive number of days in the window (endDate - startDate). */
  dateRangeDays: number;
  /** Human label, e.g. "FY2025 + YTD FY2026". */
  fyLabel: string;
  /** 1-12, mirrors the input so callers can serialise the context. */
  fiscalYearStartMonth: number;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Compute the demo date window anchored to `now`. Pure, no side effects.
 *
 * Examples (calendar FY, i.e. fiscalYearStartMonth = 1):
 *   now = 2026-04-17 -> 2025-01-01 .. 2026-04-17 (FY2025 + YTD FY2026)
 *   now = 2026-01-05 -> 2024-01-01 .. 2026-01-05 (extended: FY2024 + FY2025 + YTD FY2026)
 *   now = 2026-12-31 -> 2025-01-01 .. 2026-12-31 (FY2025 + YTD FY2026)
 */
export function computeDemoDateWindow(
  now: Date = new Date(),
  fiscalYearStartMonth: number = DEFAULT_FISCAL_YEAR_START_MONTH,
): DemoDateWindow {
  const month = clampMonth(fiscalYearStartMonth);
  const nowUtc = toUtcMidnight(now);

  const currentFyStart = fyStartContaining(nowUtc, month);
  const currentFyStartTs = Date.UTC(
    currentFyStart.year,
    currentFyStart.month - 1,
    1,
  );
  const elapsedDaysInCurrentFy = Math.floor(
    (nowUtc.getTime() - currentFyStartTs) / ONE_DAY_MS,
  );

  // Most recently completed FY starts one year before the current FY start.
  let startYear = currentFyStart.year - 1;

  // Early in the current FY? Extend back one more FY so we have a real
  // historical baseline.
  if (elapsedDaysInCurrentFy < MIN_CURRENT_FY_DAYS) {
    startYear = currentFyStart.year - 2;
  }

  const startTs = Date.UTC(startYear, month - 1, 1);
  const startDate = formatIsoDate(startTs);
  const endDate = formatIsoDate(nowUtc.getTime());
  const dateRangeDays =
    Math.floor((nowUtc.getTime() - startTs) / ONE_DAY_MS) + 1;

  const fyLabel = buildFyLabel(
    startYear,
    currentFyStart.year,
    elapsedDaysInCurrentFy >= MIN_CURRENT_FY_DAYS,
    month,
  );

  return {
    startDate,
    endDate,
    dateRangeDays,
    fyLabel,
    fiscalYearStartMonth: month,
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const ONE_DAY_MS = 24 * 60 * 60 * 1000;

function clampMonth(m: number): number {
  if (!Number.isFinite(m)) return DEFAULT_FISCAL_YEAR_START_MONTH;
  const floored = Math.trunc(m);
  if (floored < 1 || floored > 12) return DEFAULT_FISCAL_YEAR_START_MONTH;
  return floored;
}

function toUtcMidnight(d: Date): Date {
  return new Date(
    Date.UTC(d.getUTCFullYear(), d.getUTCMonth(), d.getUTCDate()),
  );
}

/**
 * Return the {year, month} of the FY start that contains `date`.
 * Fiscal year is labelled by the calendar year of its start.
 */
function fyStartContaining(
  date: Date,
  fyStartMonth: number,
): { year: number; month: number } {
  const y = date.getUTCFullYear();
  const m = date.getUTCMonth() + 1; // 1-12
  const year = m >= fyStartMonth ? y : y - 1;
  return { year, month: fyStartMonth };
}

function formatIsoDate(ts: number): string {
  const d = new Date(ts);
  const y = d.getUTCFullYear();
  const m = String(d.getUTCMonth() + 1).padStart(2, "0");
  const day = String(d.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function buildFyLabel(
  startYear: number,
  currentFyYear: number,
  fullFyComplete: boolean,
  fyStartMonth: number,
): string {
  // Calendar FY: "FY2025 + YTD FY2026".
  // Non-calendar FY: same labelling but the label refers to the fiscal-year
  // calendar-start year -- good enough for a demo UI chip.
  const parts: string[] = [];
  for (let y = startYear; y < currentFyYear; y++) {
    parts.push(`FY${y}`);
  }
  const ytdLabel = fullFyComplete
    ? `YTD FY${currentFyYear}`
    : `YTD FY${currentFyYear}`;
  parts.push(ytdLabel);

  const suffix = fyStartMonth === 1 ? "" : ` (FY starts month ${fyStartMonth})`;
  return `${parts.join(" + ")}${suffix}`;
}
